# -*- coding: utf-8 -*-
"""Prédiction du Trafic Routier Urbain à l’aide d’un Modèle Neuro-Flou Adaptatif (ANFIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYpmzyHQvq_IEonkHGqLtnpQPMfhhpV5
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import warnings
warnings.filterwarnings('ignore')

print("✅ Bibliothèques importées avec succès")
print(f"   numpy  version : {np.__version__}")
print(f"   pandas version : {pd.__version__}")

def gaussienne(x, c, sigma):
    """
    Fonction d'appartenance gaussienne.

    Paramètres
    ----------
    x     : float ou np.array  — valeur(s) d'entrée
    c     : float              — centre (moyenne)
    sigma : float              — écart-type (largeur)

    Retour
    ------
    mu : float ou np.array — degré d'appartenance dans [0, 1]

    Formule
    -------
    mu(x) = exp( -(x - c)² / (2 * sigma²) )
    """
    return np.exp(-((x - c) ** 2) / (2 * sigma ** 2))


def triangulaire(x, a, b, c):
    """
    Fonction d'appartenance triangulaire.

    Paramètres
    ----------
    a, b, c : sommets du triangle (a < b < c)

    Formule
    -------
    0             si x <= a
    (x-a)/(b-a)  si a < x <= b
    (c-x)/(c-b)  si b < x <= c
    0             si x > c
    """
    return np.maximum(0, np.minimum((x - a) / (b - a + 1e-10),
                                    (c - x) / (c - b + 1e-10)))


def trapezoidale(x, a, b, c, d):
    """
    Fonction d'appartenance trapézoïdale.

    Paramètres
    ----------
    a, b, c, d : points de la base (a < b <= c < d)

    Formule
    -------
    0             si x < a
    (x-a)/(b-a)  si a <= x < b
    1             si b <= x <= c
    (d-x)/(d-c)  si c < x <= d
    0             si x > d
    """
    gauche  = np.minimum(1, np.maximum(0, (x - a) / (b - a + 1e-10)))
    droite  = np.minimum(1, np.maximum(0, (d - x) / (d - c + 1e-10)))
    return np.minimum(gauche, droite)


def sigmoide(x, a, c):
    """
    Fonction sigmoïde floue.
    a > 0 : croissante ; a < 0 : décroissante
    """
    return 1 / (1 + np.exp(-a * (x - c)))


# ---- Test rapide des fonctions ----
x_test = np.linspace(0, 10, 200)
print("Test gaussienne(5, c=5, sigma=1.5) =",
      round(gaussienne(5, 5, 1.5), 4))   # doit être 1.0
print("Test triangulaire(5, a=2, b=5, c=8) =",
      round(triangulaire(5, 2, 5, 8), 4))  # doit être 1.0
print("✅ Fonctions d'appartenance OK")

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.suptitle("Fonctions d'appartenance — Logique Floue", fontsize=14)
x = np.linspace(0, 10, 500)

# Gaussienne
ax = axes[0, 0]
ax.plot(x, gaussienne(x, 2, 0.8),  color='blue',   label='c=2, σ=0.8')
ax.plot(x, gaussienne(x, 5, 1.2),  color='green',  label='c=5, σ=1.2')
ax.plot(x, gaussienne(x, 8, 0.6),  color='red',    label='c=8, σ=0.6')
ax.set_title("Fonction Gaussienne")
ax.set_xlabel("x"); ax.set_ylabel("μ(x)"); ax.legend(); ax.grid(True, alpha=0.3)

# Triangulaire
ax = axes[0, 1]
ax.plot(x, triangulaire(x, 0, 2, 4),  color='blue',  label='(0,2,4)')
ax.plot(x, triangulaire(x, 3, 5, 7),  color='green', label='(3,5,7)')
ax.plot(x, triangulaire(x, 6, 8, 10), color='red',   label='(6,8,10)')
ax.set_title("Fonction Triangulaire")
ax.set_xlabel("x"); ax.set_ylabel("μ(x)"); ax.legend(); ax.grid(True, alpha=0.3)

# Trapézoïdale
ax = axes[1, 0]
ax.plot(x, trapezoidale(x, 0, 1, 3, 4),  color='blue',  label='(0,1,3,4)')
ax.plot(x, trapezoidale(x, 3, 4, 6, 7),  color='green', label='(3,4,6,7)')
ax.plot(x, trapezoidale(x, 6, 7, 9, 10), color='red',   label='(6,7,9,10)')
ax.set_title("Fonction Trapézoïdale")
ax.set_xlabel("x"); ax.set_ylabel("μ(x)"); ax.legend(); ax.grid(True, alpha=0.3)

# Sigmoïde
ax = axes[1, 1]
ax.plot(x, sigmoide(x,  2, 3), color='blue',  label='a=+2, c=3 (croissante)')
ax.plot(x, sigmoide(x, -2, 7), color='red',   label='a=-2, c=7 (décroissante)')
ax.set_title("Fonction Sigmoïde")
ax.set_xlabel("x"); ax.set_ylabel("μ(x)"); ax.legend(); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("fonctions_appartenance.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : fonctions_appartenance.png")

#  Génération du jeu de données de trafic simulé
# ============================================================
# On simule 2 ans de données horaires de trafic urbain
# Profil réaliste : pics matin (7-9h) et soir (17-19h),
# réduction le weekend, bruit aléatoire

def generer_donnees_trafic(n_jours=365, graine=42):
    """
    Génère un jeu de données de trafic routier simulé.

    Variables générées
    ------------------
    - heure       : heure de la journée (0–23)
    - jour_semaine: 0=lundi ... 6=dimanche
    - est_ouvrable: 1 si jour ouvrable, 0 si weekend
    - trafic_prec : volume de trafic à t-1 (véh/h)
    - trafic      : volume de trafic à t (véh/h) — CIBLE

    Retour
    ------
    DataFrame pandas avec toutes les colonnes
    """
    np.random.seed(graine)
    donnees = []

    for jour in range(n_jours):
        jour_semaine = jour % 7         # 0=lundi, 6=dimanche
        est_ouvrable = 1 if jour_semaine < 5 else 0

        for heure in range(24):
            # --- Profil horaire de base ---
            if est_ouvrable:
                # Deux pics : matin (8h) et soir (18h)
                pic_matin = 900 * gaussienne(heure, 8, 1.5)
                pic_soir  = 1000 * gaussienne(heure, 18, 1.5)
                base      = 150  # trafic de fond
                trafic    = base + pic_matin + pic_soir
            else:
                # Weekend : un seul pic léger (13h)
                pic_midi = 500 * gaussienne(heure, 13, 2.5)
                base     = 80
                trafic   = base + pic_midi

            # --- Variations aléatoires réalistes ---
            bruit     = np.random.normal(0, 40)      # bruit gaussien
            variation = np.random.uniform(0.85, 1.15) # variation ±15%
            trafic    = max(0, trafic * variation + bruit)
            trafic    = min(trafic, 1500)             # plafond 1500 véh/h

            donnees.append({
                'heure'       : heure,
                'jour_semaine': jour_semaine,
                'est_ouvrable': est_ouvrable,
                'trafic'      : round(trafic, 1)
            })

    df = pd.DataFrame(donnees)

    # Ajouter le trafic précédent (variable autoregressive)
    df['trafic_prec'] = df['trafic'].shift(1).fillna(df['trafic'].mean())

    # Normaliser les variables dans [0, 1] pour l'ANFIS
    df['heure_norm']       = df['heure'] / 23.0
    df['est_ouvrable_norm']= df['est_ouvrable'].astype(float)
    df['trafic_prec_norm'] = df['trafic_prec'] / 1500.0
    df['trafic_norm']      = df['trafic'] / 1500.0

    return df

# Générer les données
df = generer_donnees_trafic(n_jours=365)
print(f"✅ Jeu de données généré : {len(df)} observations")
print(f"\nAperçu des données :")
print(df[['heure', 'est_ouvrable', 'trafic_prec', 'trafic']].head(10).to_string())
print(f"\nStatistiques descriptives :")
print(df['trafic'].describe().round(1))

# Visualisation du profil de trafic
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# Profil moyen par heure (jour ouvrable vs weekend)
trafic_moyen = df.groupby(['heure', 'est_ouvrable'])['trafic'].mean().reset_index()
ouvrable  = trafic_moyen[trafic_moyen['est_ouvrable'] == 1]
weekend   = trafic_moyen[trafic_moyen['est_ouvrable'] == 0]

ax = axes[0]
ax.plot(ouvrable['heure'],  ouvrable['trafic'], 'b-o', linewidth=2,
        markersize=5, label='Jour ouvrable')
ax.plot(weekend['heure'],   weekend['trafic'],  'r-s', linewidth=2,
        markersize=5, label='Weekend')
ax.set_xlabel("Heure de la journée")
ax.set_ylabel("Volume de trafic moyen (véh/h)")
ax.set_title("Profil journalier moyen du trafic urbain")
ax.legend(); ax.grid(True, alpha=0.3)
ax.set_xticks(range(0, 24, 2))

# Série temporelle sur 7 jours
ax = axes[1]
df_semaine = df.iloc[:168]  # 7 jours x 24 heures
ax.plot(range(168), df_semaine['trafic'], color='steelblue', linewidth=1.2)
ax.set_xlabel("Heure (sur 7 jours)")
ax.set_ylabel("Volume de trafic (véh/h)")
ax.set_title("Série temporelle du trafic — première semaine")
ax.axvspan(0, 24, alpha=0.1, color='red', label='Lundi')
ax.axvspan(120, 168, alpha=0.1, color='green', label='Weekend')
ax.legend(); ax.grid(True, alpha=0.3)
for i in range(0, 168, 24):
    ax.axvline(x=i, color='gray', linestyle='--', alpha=0.4)

plt.tight_layout()
plt.savefig("profil_trafic.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : profil_trafic.png")

# Division train/test
# ============================================================

def diviser_donnees(df, ratio_train=0.8):
    """
    Divise les données en ensembles d'entraînement et de test.

    Paramètres
    ----------
    df          : DataFrame avec les colonnes normalisées
    ratio_train : proportion pour l'entraînement (défaut 80%)

    Retour
    ------
    X_train, X_test, y_train, y_test : arrays numpy
    """
    # Variables d'entrée (normalisées)
    colonnes_X = ['heure_norm', 'est_ouvrable_norm', 'trafic_prec_norm']
    X = df[colonnes_X].values       # shape (N, 3)
    y = df['trafic_norm'].values    # shape (N,)

    n_train = int(len(df) * ratio_train)
    X_train, X_test = X[:n_train], X[n_train:]
    y_train, y_test = y[:n_train], y[n_train:]

    print(f"Taille entraînement : {len(X_train)} exemples ({ratio_train*100:.0f}%)")
    print(f"Taille test         : {len(X_test)} exemples ({(1-ratio_train)*100:.0f}%)")
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = diviser_donnees(df)
print(f"\nDimensions X_train : {X_train.shape}")
print(f"Dimensions y_train : {y_train.shape}")

class ANFIS:
    """
    Système d'Inférence Neuro-Flou Adaptatif (ANFIS)
    Implémentation from scratch — Sugeno de type 1.

    Architecture (5 couches)
    ------------------------
    Couche 1 : Fuzzification (fonctions gaussiennes)
    Couche 2 : Produit — forces de règles
    Couche 3 : Normalisation des forces
    Couche 4 : Conséquents linéaires (Sugeno)
    Couche 5 : Sortie globale (somme pondérée)

    Algorithme d'apprentissage : hybride
    - Passe avant  : moindres carrés (LSE) pour les conséquents
    - Passe arrière: descente de gradient pour les prémisses
    """

    def __init__(self, n_regles=6, n_entrees=3, eta=0.005):
        """
        Initialise l'ANFIS.

        Paramètres
        ----------
        n_regles  : nombre de règles floues
        n_entrees : nombre de variables d'entrée
        eta       : taux d'apprentissage (descente de gradient)
        """
        self.n_regles  = n_regles
        self.n_entrees = n_entrees
        self.eta       = eta

        # ── Paramètres PRÉMISSES ──────────────────────────────
        # premises[r, i, 0] = centre c_{r,i}
        # premises[r, i, 1] = sigma σ_{r,i}
        # Initialisation uniforme (centres espacés, sigma = 0.2)
        self.premises = np.zeros((n_regles, n_entrees, 2))
        for r in range(n_regles):
            for i in range(n_entrees):
                self.premises[r, i, 0] = (r + 1) / (n_regles + 1)  # centre
                self.premises[r, i, 1] = 0.25                        # sigma

        # ── Paramètres CONSÉQUENTS ────────────────────────────
        # Pour chaque règle r : f_r = p_{r,0}*x1 + p_{r,1}*x2 + p_{r,2}*x3 + p_{r,3}
        # Vecteur theta de taille n_regles * (n_entrees + 1)
        n_params = n_regles * (n_entrees + 1)
        self.consequents = np.random.randn(n_params) * 0.01

        # Historique pour les courbes d'apprentissage
        self.historique_train = []
        self.historique_val   = []

    # ─────────────────────────────────────────────────────────
    # COUCHES DE L'ANFIS
    # ─────────────────────────────────────────────────────────

    def couche1_fuzzification(self, X):
        """
        Couche 1 : calcule les degrés d'appartenance.

        Paramètre  : X  shape (N, n_entrees)
        Retour     : mu shape (N, n_regles, n_entrees)

        Formule    : mu[n, r, i] = exp(-(X[n,i] - c[r,i])² / (2σ[r,i]²))
        """
        N  = X.shape[0]
        mu = np.zeros((N, self.n_regles, self.n_entrees))
        for r in range(self.n_regles):
            for i in range(self.n_entrees):
                c     = self.premises[r, i, 0]
                sigma = self.premises[r, i, 1]
                mu[:, r, i] = gaussienne(X[:, i], c, sigma)
        return mu

    def couche2_regles(self, mu):
        """
        Couche 2 : force de déclenchement de chaque règle.
ax.set_ylabel("Volume de trafic (véh/h)")
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("comparaison_modeles.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : comparaison_modeles.png")
        Paramètre : mu shape (N, n_regles, n_entrees)
        Retour    : w  shape (N, n_regles)

        Formule   : w[n, r] = produit_i mu[n, r, i]
        Opérateur : produit algébrique (ET flou)
        """
        return np.prod(mu, axis=2)   # shape (N, n_regles)

    def couche3_normalisation(self, w):
        """
        Couche 3 : normalisation des forces de règles.

        Paramètre : w     shape (N, n_regles)
        Retour    : w_bar shape (N, n_regles)

        Formule   : w_bar[n, r] = w[n, r] / somme_k w[n, k]
        """
        w_somme = np.sum(w, axis=1, keepdims=True) + 1e-10
        return w / w_somme

    def couche4_5_sortie(self, X, w_bar):
        """
        Couches 4 et 5 : sortie de l'ANFIS.

        Couche 4 : contribution de chaque règle
                   O4[n, r] = w_bar[n, r] * f_r(X[n])
                   avec f_r(x) = p0*x1 + p1*x2 + p2*x3 + p3

        Couche 5 : somme totale
                   y_pred[n] = somme_r O4[n, r]

        Retour : (y_pred shape (N,), phi shape (N, n_params))
        """
        N     = X.shape[0]
        n_p   = self.n_entrees + 1
        phi   = np.zeros((N, self.n_regles * n_p))

        for r in range(self.n_regles):
            debut = r * n_p
            # Termes linéaires : w_bar * x_i
            phi[:, debut:debut + self.n_entrees] = (
                w_bar[:, r:r+1] * X
            )
            # Terme biais : w_bar
            phi[:, debut + self.n_entrees] = w_bar[:, r]

        y_pred = phi @ self.consequents   # (N,)
        return y_pred, phi

    # ─────────────────────────────────────────────────────────
    # PASSAGE AVANT COMPLET
    # ─────────────────────────────────────────────────────────

    def passage_avant(self, X):
        """
        Passage avant complet à travers les 5 couches.

        Retour : dict avec toutes les sorties intermédiaires
        """
        mu    = self.couche1_fuzzification(X)
        w     = self.couche2_regles(mu)
        w_bar = self.couche3_normalisation(w)
        y_pred, phi = self.couche4_5_sortie(X, w_bar)
        return {
            'mu'    : mu,
            'w'     : w,
            'w_bar' : w_bar,
            'phi'   : phi,
            'y_pred': y_pred
        }

    # ─────────────────────────────────────────────────────────
    # MÉTHODE DES MOINDRES CARRÉS (LSE)
    # ─────────────────────────────────────────────────────────

    def lse(self, phi, y):
        """
        Identifie les paramètres conséquents par moindres carrés.

        Formule : theta = (Phi^T Phi)^{-1} Phi^T y

        Paramètres
        ----------
        phi : matrice des régresseurs (N, n_params)
        y   : cibles (N,)
        """
        # Ajout d'une régularisation Ridge pour éviter la singularité
        lamb = 1e-4
        A    = phi.T @ phi + lamb * np.eye(phi.shape[1])
        b    = phi.T @ y
        self.consequents = np.linalg.solve(A, b)

    # ─────────────────────────────────────────────────────────
    # DESCENTE DE GRADIENT (paramètres prémisses)
    # ─────────────────────────────────────────────────────────

    def descente_gradient(self, X, y, res):
        """
        Met à jour les paramètres prémisses par descente de gradient.

        Utilise la règle de la chaîne à travers les 5 couches.

        dE/dc_{r,i} = dE/dy * dy/dw_bar_r * dw_bar_r/dw_r
                      * dw_r/dmu_{r,i} * dmu_{r,i}/dc_{r,i}
        """
        N     = X.shape[0]
        mu    = res['mu']
        w     = res['w']
        w_bar = res['w_bar']
        y_pred= res['y_pred']
        erreur= y_pred - y           # dE/dy_pred, shape (N,)

        n_p    = self.n_entrees + 1
        w_somme= np.sum(w, axis=1) + 1e-10   # shape (N,)

        for r in range(self.n_regles):
            # ── f_r(X) : sortie de la règle r ────────────────
            debut  = r * n_p
            theta_r = self.consequents[debut:debut + n_p]
            X_aug   = np.hstack([X, np.ones((N, 1))])  # (N, n_entrees+1)
            f_r     = X_aug @ theta_r                   # (N,)

            # ── dy/dw_bar_r ───────────────────────────────────
            # y = somme_k w_bar_k * f_k
            # dy/dw_bar_r = f_r
            dy_dwbar = f_r    # shape (N,)

            # ── dw_bar_r/dw_r ─────────────────────────────────
            # w_bar_r = w_r / W  où W = somme_k w_k
            # dw_bar_r/dw_r = (W - w_r) / W²
            dwbar_dw = (w_somme - w[:, r]) / (w_somme ** 2)

            for i in range(self.n_entrees):
                c     = self.premises[r, i, 0]
                sigma = self.premises[r, i, 1]

                # ── dw_r/dmu_{r,i} ────────────────────────────
                # w_r = produit_{j} mu_{r,j}
                # dw_r/dmu_{r,i} = produit_{j≠i} mu_{r,j}
                #                = w_r / mu_{r,i}
                dw_dmu = w[:, r] / (mu[:, r, i] + 1e-10)

                # ── dmu_{r,i}/dc_{r,i} ────────────────────────
                # mu = exp(-(x-c)²/(2σ²))
                # dmu/dc = mu * (x - c) / σ²
                xi        = X[:, i]
                dmu_dc    = mu[:, r, i] * (xi - c) / (sigma ** 2)
                dmu_dsigma= mu[:, r, i] * (xi - c)**2 / (sigma ** 3)

                # ── Gradient total (règle de la chaîne) ───────
                facteur  = erreur * dy_dwbar * dwbar_dw * dw_dmu
                grad_c   = np.mean(facteur * dmu_dc)
                grad_sig = np.mean(facteur * dmu_dsigma)

                # ── Mise à jour ────────────────────────────────
                self.premises[r, i, 0] -= self.eta * grad_c
                self.premises[r, i, 1] -= self.eta * grad_sig

                # Contrainte : sigma strictement positif
                self.premises[r, i, 1] = max(self.premises[r, i, 1], 0.01)
                # Contrainte : centre dans [0, 1] (données normalisées)
                self.premises[r, i, 0] = np.clip(self.premises[r, i, 0], 0, 1)

    # ─────────────────────────────────────────────────────────
    # BOUCLE D'ENTRAÎNEMENT PRINCIPALE
    # ─────────────────────────────────────────────────────────

    def entrainer(self, X_train, y_train, X_val, y_val, n_epoques=80):
        """
        Entraîne l'ANFIS par l'algorithme hybride.

        Pour chaque époque :
          1. Passe avant  → calculer mu, w, w_bar, phi
          2. LSE          → optimiser les conséquents (theta)
          3. Passe avant  → recalculer y_pred avec nouveaux theta
          4. Passe arrière→ gradient descent sur les prémisses

        Paramètres
        ----------
        X_train, y_train : données d'entraînement
        X_val,   y_val   : données de validation
        n_epoques        : nombre d'itérations
        """
        print("=" * 55)
        print("  DÉBUT DE L'ENTRAÎNEMENT ANFIS")
        print(f"  Règles : {self.n_regles} | "
              f"Entrées : {self.n_entrees} | "
              f"Éta : {self.eta}")
        print("=" * 55)

        for epoque in range(1, n_epoques + 1):

            # ── Passe avant (train) ──────────────────────────
            res_train = self.passage_avant(X_train)

            # ── Moindres carrés (LSE) ────────────────────────
            self.lse(res_train['phi'], y_train)

            # ── Recalcul avec nouveaux conséquents ───────────
            res_train = self.passage_avant(X_train)

            # ── Passe arrière (gradient) ─────────────────────
            self.descente_gradient(X_train, y_train, res_train)

            # ── Calcul des erreurs ───────────────────────────
            rmse_train = self.rmse(y_train, res_train['y_pred'])
            res_val    = self.passage_avant(X_val)
            rmse_val   = self.rmse(y_val, res_val['y_pred'])

            self.historique_train.append(rmse_train)
            self.historique_val.append(rmse_val)

            if epoque % 10 == 0 or epoque == 1:
                print(f"  Époque {epoque:3d}/{n_epoques} | "
                      f"RMSE train : {rmse_train:.6f} | "
                      f"RMSE val : {rmse_val:.6f}")

        print("=" * 55)
        print("  ENTRAÎNEMENT TERMINÉ")
        print(f"  RMSE final train : {self.historique_train[-1]:.6f}")
        print(f"  RMSE finale val  : {self.historique_val[-1]:.6f}")
        print("=" * 55)

    # ─────────────────────────────────────────────────────────
    # PRÉDICTION
    # ─────────────────────────────────────────────────────────

    def predire(self, X):
        """
        Génère les prédictions pour X.
        Retour : y_pred shape (N,)
        """
        res = self.passage_avant(X)
        return np.clip(res['y_pred'], 0, 1)   # Forcer dans [0, 1]

    # ─────────────────────────────────────────────────────────
    # MÉTRIQUES
    # ─────────────────────────────────────────────────────────

    @staticmethod
    def rmse(y_vrai, y_pred):
        """Erreur quadratique moyenne racine."""
        return np.sqrt(np.mean((y_vrai - y_pred) ** 2))

    @staticmethod
    def mae(y_vrai, y_pred):
        """Erreur absolue moyenne."""
        return np.mean(np.abs(y_vrai - y_pred))

    @staticmethod
    def mape(y_vrai, y_pred):
        """Erreur absolue moyenne en pourcentage."""
        masque = np.abs(y_vrai) > 1e-6
        return 100 * np.mean(
            np.abs((y_vrai[masque] - y_pred[masque]) / y_vrai[masque])
        )

    @staticmethod
    def r2(y_vrai, y_pred):
        """Coefficient de détermination R²."""
        ss_res = np.sum((y_vrai - y_pred) ** 2)
        ss_tot = np.sum((y_vrai - np.mean(y_vrai)) ** 2)
        return 1 - ss_res / (ss_tot + 1e-10)


print("✅ Classe ANFIS définie avec succès")
print(f"   Méthodes disponibles :")
for m in ['couche1_fuzzification', 'couche2_regles', 'couche3_normalisation',
          'couche4_5_sortie', 'lse', 'descente_gradient', 'entrainer',
          'predire', 'rmse', 'mae', 'mape', 'r2']:
    print(f"   - {m}")

# Créer l'instance ANFIS
anfis = ANFIS(
    n_regles  = 8,      # 8 règles floues
    n_entrees = 3,      # heure, est_ouvrable, trafic_prec
    eta       = 0.008   # taux d'apprentissage
)

print("Paramètres initiaux des prémisses :")
print("  Règle | Variable | Centre  | Sigma")
for r in range(anfis.n_regles):
    for i in range(anfis.n_entrees):
        noms = ['heure', 'jour ', 'traf.']
        print(f"    R{r+1}  |  {noms[i]} "
              f"  | {anfis.premises[r,i,0]:.3f} | "
              f"{anfis.premises[r,i,1]:.3f}")
    print()

# Entraîner le modèle
anfis.entrainer(
    X_train   = X_train,
    y_train   = y_train,
    X_val     = X_test,
    y_val     = y_test,
    n_epoques = 80
)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(anfis.historique_train, 'b-', linewidth=2, label='Entraînement')
plt.plot(anfis.historique_val,   'r--',linewidth=2, label='Validation')
plt.xlabel("Époque")
plt.ylabel("RMSE (normalisée)")
plt.title("Courbe d'apprentissage — ANFIS")
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
# Zoom sur les 50 dernières époques
plt.plot(anfis.historique_train[-50:], 'b-', linewidth=2, label='Entraînement')
plt.plot(anfis.historique_val[-50:],   'r--',linewidth=2, label='Validation')
plt.xlabel("Époque (50 dernières)")
plt.ylabel("RMSE (normalisée)")
plt.title("Zoom — convergence finale")
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("courbe_apprentissage.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : courbe_apprentissage.png")



# Prédictions en données normalisées
y_pred_norm = anfis.predire(X_test)

# Dénormaliser pour avoir les vraies valeurs (véh/h)
y_pred_reel = y_pred_norm * 1500
y_test_reel = y_test * 1500

# Calcul des métriques
rmse_val = anfis.rmse(y_test_reel, y_pred_reel)
mae_val  = anfis.mae(y_test_reel, y_pred_reel)
mape_val = anfis.mape(y_test_reel, y_pred_reel)
r2_val   = anfis.r2(y_test_reel, y_pred_reel)

print("=" * 50)
print("  RÉSULTATS DU MODÈLE ANFIS — Ensemble de Test")
print("=" * 50)
print(f"  RMSE  (véh/h)  : {rmse_val:.2f}")
print(f"  MAE   (véh/h)  : {mae_val:.2f}")
print(f"  MAPE  (%)      : {mape_val:.2f}%")
print(f"  R²             : {r2_val:.4f}")
print("=" * 50)
print(f"\n  Interprétation :")
print(f"  - En moyenne, l'erreur est de {mae_val:.1f} véh/h")
print(f"  - Le modèle explique {r2_val*100:.1f}% de la variance")

# Choisir 48 heures (2 jours) pour la visualisation
n_vis = 48
y_vis_reel = y_test_reel[:n_vis]
y_vis_pred = y_pred_reel[:n_vis]

fig, axes = plt.subplots(2, 1, figsize=(16, 10))

# --- Graphique 1 : Série temporelle ----
ax = axes[0]
ax.plot(range(n_vis), y_vis_reel, 'b-o', linewidth=2,
        markersize=4, label='Valeurs réelles')
ax.plot(range(n_vis), y_vis_pred, 'r--s', linewidth=2,
        markersize=4, label='Prédictions ANFIS')

# Bande d'erreur
ax.fill_between(range(n_vis),
                y_vis_pred - mae_val,
                y_vis_pred + mae_val,
                alpha=0.2, color='red', label=f'±MAE ({mae_val:.0f} véh/h)')
ax.set_xlabel("Heure")
ax.set_ylabel("Volume de trafic (véh/h)")
ax.set_title("Prédiction ANFIS vs Valeurs réelles — 48 heures")
ax.legend(loc='upper right')
ax.grid(True, alpha=0.3)
ax.set_xticks(range(0, n_vis, 6))
ax.set_xticklabels([f"{h%24}h" for h in range(0, n_vis, 6)])

# --- Graphique 2 : Nuage de points réel vs prédit ----
ax = axes[1]
min_v = min(y_test_reel.min(), y_pred_reel.min())
max_v = max(y_test_reel.max(), y_pred_reel.max())
ax.scatter(y_test_reel, y_pred_reel, alpha=0.3, s=10, color='steelblue')
ax.plot([min_v, max_v], [min_v, max_v], 'r-', linewidth=2,
        label='Prédiction parfaite (y=x)')
ax.set_xlabel("Valeurs réelles (véh/h)")
ax.set_ylabel("Valeurs prédites (véh/h)")
ax.set_title(f"Nuage de points — R² = {r2_val:.4f}")
ax.legend(); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("predictions_anfis.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : predictions_anfis.png")

#               apprises par l'ANFIS
# ============================================================

noms_variables = ['Heure (normalisée)', 'Jour (0=WE, 1=Ouv)', 'Trafic passé (normalisé)']
couleurs       = ['blue', 'green', 'red', 'purple', 'orange', 'brown', 'pink', 'gray']

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Fonctions d'appartenance apprises par l'ANFIS", fontsize=13)

for i in range(anfis.n_entrees):
    ax   = axes[i]
    x_ax = np.linspace(0, 1, 300)

    for r in range(anfis.n_regles):
        c     = anfis.premises[r, i, 0]
        sigma = anfis.premises[r, i, 1]
        mu    = gaussienne(x_ax, c, sigma)
        ax.plot(x_ax, mu, color=couleurs[r],
                linewidth=2, label=f'Règle {r+1}')

    ax.set_xlabel("Valeur normalisée")
    ax.set_ylabel("Degré d'appartenance μ")
    ax.set_title(noms_variables[i])
    ax.legend(loc='upper right', fontsize=7)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(0, 1.05)

plt.tight_layout()
plt.savefig("fa_apprises.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : fa_apprises.png")

# ============================================================
# On compare l'ANFIS à des modèles classiques implémentés
# from scratch également

# ── Régression Linéaire (from scratch) ─────────────────────
class RegressionLineaire:
    """Régression linéaire par moindres carrés."""

    def __init__(self):
        self.poids = None

    def entrainer(self, X, y):
        """Formule directe : w = (X^T X)^{-1} X^T y"""
        X_aug     = np.hstack([X, np.ones((X.shape[0], 1))])
        A         = X_aug.T @ X_aug + 1e-6 * np.eye(X_aug.shape[1])
        self.poids = np.linalg.solve(A, X_aug.T @ y)

    def predire(self, X):
        X_aug = np.hstack([X, np.ones((X.shape[0], 1))])
        return X_aug @ self.poids


# ── Réseau de Neurones MLP (from scratch) ──────────────────
class MLP:
    """
    Réseau de neurones multicouche — 1 couche cachée.
    Activation : ReLU sur la couche cachée, linéaire en sortie.
    """

    def __init__(self, n_entrees=3, n_caches=16, eta=0.01):
        self.eta = eta
        # Initialisation Xavier
        self.W1 = np.random.randn(n_entrees, n_caches) * np.sqrt(2 / n_entrees)
        self.b1 = np.zeros(n_caches)
        self.W2 = np.random.randn(n_caches, 1) * np.sqrt(2 / n_caches)
        self.b2 = np.zeros(1)

    def relu(self, x):
        return np.maximum(0, x)

    def predire(self, X):
        self.z1 = X @ self.W1 + self.b1
        self.a1 = self.relu(self.z1)
        return (self.a1 @ self.W2 + self.b2).flatten()

    def entrainer_epoque(self, X, y):
        N      = X.shape[0]
        y_pred = self.predire(X)
        erreur = y_pred - y

        # Rétropropagation
        dL_dy  = erreur / N
        dW2    = self.a1.T @ dL_dy.reshape(-1, 1)
        db2    = np.sum(dL_dy)
        dL_da1 = dL_dy.reshape(-1, 1) @ self.W2.T
        dL_dz1 = dL_da1 * (self.z1 > 0)
        dW1    = X.T @ dL_dz1
        db1    = np.sum(dL_dz1, axis=0)

        self.W2 -= self.eta * dW2
        self.b2 -= self.eta * db2
        self.W1 -= self.eta * dW1
        self.b1 -= self.eta * db1
        return ANFIS.rmse(y, y_pred)


# ── Entraînement des modèles de référence ──────────────────
print("Entraînement des modèles de référence...")

# Régression linéaire
rl = RegressionLineaire()
rl.entrainer(X_train, y_train)
pred_rl = rl.predire(X_test) * 1500

# MLP
mlp = MLP(n_entrees=3, n_caches=24, eta=0.005)
for ep in range(200):
    mlp.entrainer_epoque(X_train, y_train)
pred_mlp = np.clip(mlp.predire(X_test), 0, 1) * 1500

print("✅ Modèles de référence entraînés")

# CELLULE 15 — Tableau comparatif des résultats
# ============================================================

def calculer_metriques(y_vrai, y_pred, nom):
    """Calcule et retourne toutes les métriques pour un modèle."""
    rmse = ANFIS.rmse(y_vrai, y_pred)
    mae  = ANFIS.mae(y_vrai, y_pred)
    mape = ANFIS.mape(y_vrai, y_pred)
    r2   = ANFIS.r2(y_vrai, y_pred)
    return {'Modèle': nom, 'RMSE': rmse, 'MAE': mae, 'MAPE (%)': mape, 'R²': r2}

resultats = []
resultats.append(calculer_metriques(y_test_reel, pred_rl,         "Régression Linéaire"))
resultats.append(calculer_metriques(y_test_reel, pred_mlp,        "Réseau de Neurones (MLP)"))
resultats.append(calculer_metriques(y_test_reel, y_pred_reel,     "ANFIS (notre modèle)"))

df_res = pd.DataFrame(resultats).set_index('Modèle')
df_res = df_res.round(3)

print("\n" + "=" * 65)
print("  COMPARAISON DES MODÈLES — Ensemble de Test")
print("=" * 65)
print(df_res.to_string())
print("=" * 65)
print(f"\n✅ Le modèle ANFIS obtient le meilleur R² = {r2_val:.4f}")

# CELLULE 16 — Graphique comparatif des modèles
# ============================================================

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
n_comp     = 72    # 3 jours
x_comp     = range(n_comp)
reel_comp  = y_test_reel[:n_comp]

for ax, (y_comp, nom, couleur) in zip(axes, [
    (pred_rl[:n_comp],    "Régression Linéaire",  "orange"),
    (pred_mlp[:n_comp],   "Réseau de Neurones",   "green"),
    (y_pred_reel[:n_comp],"ANFIS",                "blue"),
]):
    ax.plot(x_comp, reel_comp, 'k-',  linewidth=1.5, label='Réel')
    ax.plot(x_comp, y_comp,    '--',  linewidth=1.5,
            color=couleur, label=nom)

    r2_m    = ANFIS.r2(reel_comp, y_comp)
    rmse_m  = ANFIS.rmse(reel_comp, y_comp)
    ax.set_title(f"{nom}\nR²={r2_m:.3f} | RMSE={rmse_m:.1f}")
    ax.legend(fontsize=8)
    ax.set_xlabel("Heure"); ax.set_ylabel("Trafic (véh/h)")
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("comparaison_modeles.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : comparaison_modeles.png")

# CELLULE 17 — Analyse des erreurs
# ============================================================

erreurs      = y_test_reel - y_pred_reel
erreurs_abs  = np.abs(erreurs)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("Analyse des erreurs — Modèle ANFIS", fontsize=13)

# Distribution des erreurs
ax = axes[0]
ax.hist(erreurs, bins=50, color='steelblue', edgecolor='white', alpha=0.8)
ax.axvline(0, color='red', linewidth=2, label='Zéro')
ax.axvline(erreurs.mean(), color='orange', linewidth=2,
           label=f'Moyenne ({erreurs.mean():.1f})')
ax.set_xlabel("Erreur (véh/h)")
ax.set_ylabel("Fréquence")
ax.set_title("Distribution des erreurs")
ax.legend(); ax.grid(True, alpha=0.3)

# Erreur absolue par heure de la journée
ax     = axes[1]
heures = df.iloc[int(len(df)*0.8):]['heure'].values[:len(erreurs_abs)]
err_h  = pd.DataFrame({'heure': heures, 'erreur_abs': erreurs_abs})
moy_h  = err_h.groupby('heure')['erreur_abs'].mean()
ax.bar(moy_h.index, moy_h.values, color='steelblue', alpha=0.8)
ax.set_xlabel("Heure de la journée")
ax.set_ylabel("MAE moyen (véh/h)")
ax.set_title("Erreur absolue moyenne par heure")
ax.grid(True, alpha=0.3, axis='y')

# Erreurs cumulées (boîtes à moustaches)
ax = axes[2]
ax.boxplot([erreurs], tick_labels=['ANFIS'], vert=True,
           patch_artist=True,
           boxprops=dict(facecolor='lightblue', color='blue'),
           medianprops=dict(color='red', linewidth=2))
ax.set_ylabel("Erreur (véh/h)")
ax.set_title("Boîte à moustaches des erreurs")
ax.grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.savefig("analyse_erreurs.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : analyse_erreurs.png")

# CELLULE 18 — Surface floue (visualisation 3D)
# ============================================================
# On trace la surface de sortie de l'ANFIS en faisant varier
# deux entrées pendant que la troisième est fixée

print("Génération de la surface de sortie floue...")

h_range   = np.linspace(0, 1, 40)    # heure normalisée
tp_range  = np.linspace(0, 1, 40)    # trafic passé normalisé
H, TP     = np.meshgrid(h_range, tp_range)

# Fixer "est_ouvrable" = 1 (jour ouvrable)
Z = np.zeros_like(H)
for i in range(H.shape[0]):
    for j in range(H.shape[1]):
        x_ij  = np.array([[H[i, j], 1.0, TP[i, j]]])
        Z[i,j]= anfis.predire(x_ij)[0] * 1500

fig = plt.figure(figsize=(14, 6))

# Vue 3D
ax = fig.add_subplot(121, projection='3d')
surf = ax.plot_surface(H * 23, TP * 1500, Z,
                       cmap='viridis', alpha=0.85, linewidth=0)
ax.set_xlabel("Heure (h)")
ax.set_ylabel("Trafic passé (véh/h)")
ax.set_zlabel("Trafic prédit (véh/h)")
ax.set_title("Surface de sortie ANFIS\n(Jour ouvrable)")
fig.colorbar(surf, ax=ax, shrink=0.5)

# Vue en carte de chaleur (heatmap)
ax2 = fig.add_subplot(122)
im  = ax2.contourf(H * 23, TP * 1500, Z, levels=20, cmap='viridis')
ax2.set_xlabel("Heure (h)")
ax2.set_ylabel("Trafic passé (véh/h)")
ax2.set_title("Vue de dessus — Surface ANFIS")
plt.colorbar(im, ax=ax2, label='Trafic prédit (véh/h)')

plt.tight_layout()
plt.savefig("surface_floue.png", dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphique sauvegardé : surface_floue.png")

def predire_trafic(heure, est_ouvrable, trafic_prec):
    """
    Prédit le volume de trafic pour un moment donné.

    Paramètres
    ----------
    heure         : int   — heure de la journée (0–23)
    est_ouvrable  : int   — 1 si jour ouvrable, 0 si weekend
    trafic_prec   : float — trafic observé à t-1 (véh/h)

    Retour
    ------
    trafic_predit : float (véh/h)
    """
    x = np.array([[
        heure / 23.0,
        float(est_ouvrable),
        trafic_prec / 1500.0
    ]])
    pred = anfis.predire(x)[0] * 1500
    return max(0, pred)


# Tests
print("=" * 50)
print("  PRÉDICTIONS INTERACTIVES")
print("=" * 50)

cas_tests = [
    (8,  1, 400,  "Lundi 8h — trafic modéré avant"),
    (18, 1, 900,  "Vendredi 18h — pic du soir"),
    (2,  0, 80,   "Samedi 2h — nuit calme"),
    (13, 0, 300,  "Dimanche 13h — midi weekend"),
    (7,  1, 150,  "Mercredi 7h — début de matinée"),
]

for heure, jour, prec, description in cas_tests:
    pred = predire_trafic(heure, jour, prec)
    niveau = ("🟢 FAIBLE" if pred < 300 else
              "🟡 MOYEN"  if pred < 700 else
              "🔴 DENSE")
    print(f"\n  {description}")
    print(f"  → Trafic prédit : {pred:.0f} véh/h  {niveau}")

print("\n" + "=" * 50)

print("\n" + "=" * 60)
print("  RÉSUMÉ FINAL — PROJET ANFIS TRAFIC ROUTIER")
print("  Université de Kinshasa — Master 2 — 2025-2026")
print("=" * 60)

print(f"""
  ARCHITECTURE DU MODÈLE
  ─────────────────────
  • Type          : ANFIS (Sugeno de type 1)
  • Entrées       : 3 (heure, type de jour, trafic passé)
  • Règles floues : {anfis.n_regles}
  • FA            : Gaussiennes (apprises par gradient)
  • Apprentissage : Hybride (LSE + descente de gradient)
  • Éta           : {anfis.eta}

  DONNÉES
  ────────
  • Observations  : {len(df)}
  • Entraînement  : {len(X_train)} ({80}%)
  • Test          : {len(X_test)} ({20}%)

  PERFORMANCES (sur l'ensemble de test)
  ──────────────────────────────────────
  • RMSE  : {rmse_val:.2f} véh/h
  • MAE   : {mae_val:.2f} véh/h
  • MAPE  : {mape_val:.2f}%
  • R²    : {r2_val:.4f} ({r2_val*100:.1f}% de variance expliquée)

  FICHIERS GÉNÉRÉS
  ─────────────────
  • fonctions_appartenance.png
  • profil_trafic.png
  • courbe_apprentissage.png
  • predictions_anfis.png
  • comparaison_modeles.png
  • analyse_erreurs.png
  • surface_floue.png
""")

# Sauvegarder les résultats dans un CSV
df_res.to_csv("resultats_comparaison.csv")
print("  ✅ Résultats sauvegardés dans resultats_comparaison.csv")

# Sauvegarder les prédictions
pd.DataFrame({
    'reel'       : y_test_reel,
    'anfis'      : y_pred_reel,
    'reg_lin'    : pred_rl,
    'mlp'        : pred_mlp,
}).to_csv("predictions.csv", index=False)
print("  ✅ Prédictions sauvegardées dans predictions.csv")
print("\n  FIN DU PROJET\n" + "=" * 60)
